version: '3.7'

services:
  tcg-api-bs:
    container_name: tcg-api-bs
    build:
      dockerfile: ./docker/Dockerfile.local
      context: .
    restart: always
    ports:
      - "8322:8080"
    volumes:
      - .:/go/src/app/
      - .env.local:/go/src/app/.env
    environment:
      APP_ENV: local
    networks:
      network-horeca:
        aliases:
          - tcg-api-bs.eggsmartpos.local

    # healthcheck:
    #   test: curl -f http://tcg-api-bs.eggsmartpos.local
    #   start_period: 30s
    #   interval: 30s
    #   timeout: 15s
    #   retries: 3

networks:
  network-horeca:
    external: true